name: Test schvalid

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y python3-dev
        pip install --upgrade pip
        pip install -e .[dev,test]
    - name: Test with pytest
      run: |
        (cd tests/ && python3 -m pytest --html=report.html --self-contained-html .)
    - uses: actions/upload-artifact@v3
      with:
        name: Test Report
        path: tests/report.html
